import difflib
import pypinyin

# 音乐术语字典
music_terms = {
    'A cappella': '无伴奏的声乐演唱',
    'A punta d\'arco': '用弓尖演奏',
    'Abbandonamente': '放任地，无拘束地',
    'Abbellimenti': '装饰音群',
    'Accarezzevole': '爱抚的，抚摸着',
    'Acciaccato': '重音的，突强的',
    'Accordatura': '调音，定音法',
    'Acustica': '声学的',
    'Affetto': '柔情的',
    'Agitato': '激动地，不宁地，惊慌地',
    'Agogica': '速度表情法',
    'Aggradevole': '妩媚的，令人怜爱的',
    'Al ponticello': '在琴桥附近演奏',
    'Al taco': '用弓根部演奏',
    'Alberti bass': '阿尔贝蒂低音，分解和弦伴奏音型',
    'Alla cadenza': '如华彩段般',
    'Alla corda': '靠近琴弦演奏',
    'Alla marcia': '进行曲风格',
    'Alla polacca': '波兰舞曲风格的',
    'Alla siciliana': '西西里舞曲风格的',
    'Alla zingara': '吉普赛风格的',
    'Angoscioso': '焦虑不安地，痛苦地',
    'Animato': '有生气的，活跃的',
    'Appoggiando': '倚音的',
    'Appoggiatura doppia': '双倚音',
    'Armonici artificiali': '人工泛音',
    'Arpeggiando': '琶音式的',
    'Arpeggiato': '分散和弦的',
    'Articolazione': '发音法，衔接法',
    
    'Bariolage': '快速交替演奏空弦和按弦',
    'Basso continuo': '通奏低音',
    'Basso ostinato': '固定低音，反复低音音型',
    'Battement': '装饰音，颤音',
    'Bicinium': '双声部曲，二重唱',
    'Bicordo': '双音',
    'Bisbigliando': '低语般的，极轻的颤音',
    'Bitonalità': '双调性',
    'Bizzarro': '古怪的',
    'Brillante': '华丽而灿烂的',
    'Buffo': '滑稽的',
    
    'Cadenza composta': '复合终止式',
    'Cadenza doppia': '双重终止式',
    'Cadenza evitata': '回避终止式',
    'Cadenza fiorita': '华彩终止式',
    'Cadenza plagale': '变格终止式',
    'Camminando': '流畅地，从容不迫地',
    'Cantabile': '如歌的',
    'Cantabile parlante': '如说话般的歌唱',
    'Canto fiorito': '华丽的歌唱风格',
    'Canto spianato': '平稳的歌唱风格',
    'Chiavette': '高位谱号系统',
    'Cluster': '音团，音簇',
    'Col legno battuto': '用弓杆敲击琴弦',
    'Col legno tratto': '用弓杆摩擦琴弦',
    'Coloratura': '花腔，装饰性的旋律段落',
    'Colpo d\'arco': '弓击音',
    'Combinazione di registri': '音栓组合',
    'Combinazione toni': '音的组合',
    'Con brio': '有精神，有活力的',
    'Con grazia': '优美的',
    'Contrappunto doppio': '双重对位法',
    'Contrappunto invertibile': '可转位对位法',
    'Contrappunto osservato': '严格对位法',
    'Corda vuota': '空弦',
    'A tempo': '速度还原',
    'accel.': '加速',
    'Accelerando': '加速的',
    'Adagio': '柔板；从容的；悠闲的',
    'Affettuoso': '深情的',
    'Al fine': '直到结束',
    'Allegretto': '小快板；稍快；比allegro稍慢的速度',
    'Allegro': '快板；欢快地；较活泼的速度',
    'Allegro molto': '非常快速的',
    'Andante': '行板；徐缓；行进的',
    'Andante con moto': '行进速度，带有动作感的',
    'Appassionato': '充满激情的',
    'Arioso': '空灵的，歌唱的',
    'Arpeggio': '琶音',
    'Attacca': '紧接着演奏',
    'Ben marcato': '清晰地强调',
    'Coda': '尾声，结尾',
    'Col legno': '用木头部分击打弦',
    'Con anima': '带有灵魂的，有激情的',
    'Con moto': '带有运动感的，带有速度的',
    'Crescendo': '渐强的',
    'D.C. al Fine': '从头开始，到终点为止',
    'dim.': '渐弱',
    'Diminuendo': '渐弱的',
    'Divisi': '分声部的',
    'Dolce': '甜美的，柔和的',
    'Doloroso': '悲伤的，哀伤的',
    'Energico': '充满能量的，强而有力的',
    'Espressivo': '富有表现力的',
    'Fermata': '停顿，暂停',
    'Forte': '强的',
    'Fortissimo': '非常强的',
    'Furioso': '愤怒的，狂暴的',
    'Giocoso': '欢快的，幽默的',
    'Glissando': '滑奏',
    'Grave': '庄板；慢而庄严的；严峻的',
    'Grazioso': '优雅的，柔美的',
    'Lamentoso': '悲叹的，哀伤的',
    'Largo': '广板；宽广的；庄严的',
    'loco': '回到标准音高(前面有8va)',
    'Legato': '连奏的',
    'Leggiero': '轻快的',
    'Lento': '慢板；慢慢的',
    'Lied': '歌曲（特别是德国艺术歌曲）',
    'Maestoso': '庄严的，威严的',
    'Movido': '活跃的',
    'Marcato': '强调的',
    'Marziale': '庄严的，进行曲风格的',
    'Meno': '少些；减少',
    'Meno mosso': '慢些（少快点）',
    'Misterioso': '神秘的',
    'molto accel.': '更快的加速',
    'molto rall.': '更多的渐慢以及扩张',
    'Non troppo': '不太，稍微',
    'Patetico': '悲怆的，感伤的',
    'Pesante': '慢速度；沉重的（每个音用一些重音）',
    'Pianissimo': '非常弱的',
    'Piano': '弱的',
    'Piu mosso': '更快些被激动了的',
    'Piu intenso': '更强烈的',
    'poco a poco': '逐渐地',
    'pizz': '把右手小指放在琴码处把弦蒙住，用其他指头拨弦，声音朦胧短促。',
    'Presto': '急板；迅速地',
    'Quasi': '类似于，好像',
    'Rallentando': '渐慢',
    'Risoluto': '坚定的，坚决的',
    'rit.': '渐慢的',
    'rall. poco a poco': '逐渐地渐慢',
    'Rubato': '自由变化的节奏',
    'Scherzando': '玩笑般的',
    'sempre stesso tempo': '始终保持相同的速度',
    'Scherzo': '玩笑曲',
    'Semplice': '简单的',
    'Serioso': '严肃的，认真地',
    'Sordino': '弱音器',
    'Sostenuto': '持续的，延长的',
    'Staccato': '断奏的',
    'stacc. e marcato': '断奏且强调的',
    'Stretto': '加速紧凑些',
    'Subito': '突然(sub.)',
    'Tenuto': '保持音符的时值',
    'Tambora':'像打击乐器一样把手放在音对应的弦上并移到靠近琴码的位置，使用i m a 指依次敲击弦',
    'Tranquillo': '平静的',
    'Tempo primo': '原速，速度还原全曲速度',
    'Tempo primo - deciso': '回到原速且坚定地演奏',
    'Tutti': '全体，所有乐器',
    'Vivace': '活跃的；快速的；敏捷的',
    'Vivo': '活泼；生动地；充满活力的',
    'Volante': '飞快的，轻盈的',
    'Zart': '柔和的，优美的',
    'Ab libitum': '随意的，自由发挥的',
    'Bellicoso': '战斗般的，好战的',
    'Bravura': '华丽的，炫技的',
    'Calando': '渐弱且渐慢',
    'Capriccioso': '随性的，任性的',
    'Con spirito': '带有精神的',
    'Con tenerezza': '温柔地',
    'Deciso': '坚定的，果断的',
    'Delicato': '精致的，优美的',
    'Drammatico': '戏剧性的',
    'Elegante': '优雅的，高贵的',
    'Eroico': '英雄的，壮丽的',
    'Feroce': '凶猛的，激烈的',
    'Festivo': '欢庆的，节日般的',
    'Fluente': '流畅的',
    'Grandioso': '宏伟的，壮丽的',
    'Grazioso con moto': '优美且富有动感的',
    'Impetuoso': '急促的，热情的',
    'Incalzando': '加急渐快并渐强',
    'Inquieto': '不安的，焦躁的',
    'Lacrimoso': '悲伤的，哭泣般的',
    'Languido': '柔弱的，无力的',
    'Liberamente': '自由的',
    'Maestoso con brio': '庄严且活力充沛的',
    'Melancolico': '忧郁的',
    'Misterioso con moto': '神秘且带有动感的',
    'Nobilmente': '高贵的，庄重的',
    'Nostalgico': '怀旧的',
    'Ondeggiante': '波动的，起伏的',
    'Ostinato': '固执的，反复的',
    'Pastorale': '田园风格的',
    'Patetico con dolore': '悲怆且痛苦的',
    'Pomposo': '浮夸的，华丽的',
    'Religioso': '虔诚的，宗教般的',
    'Rigoroso': '严格的，精确的',
    'Rustico': '乡村风格的',
    'Sognando': '梦幻般的',
    'Solenne': '庄严的',
    'Spianato': '平静的，均匀的',
    'Spirituoso': '精神饱满的',
    'Tenebroso': '阴暗的，神秘的',
    'Tosto': '快速的，敏捷的',
    'Trionfale': '凯旋的，胜利的',
    'Un poco': '稍微，一点',
    'Unisono': '同音的',
    'Vigoroso': '有力的，充满活力的',
    'Virtuoso': '炫技的，精湛的',
    'Zeloso': '热情的，热忱的',
    'Zingarese': '吉普赛风格的',
    'Alzapua': '弗拉门戈吉他技巧，用拇指连续向下和向上扫弦',
    'Apoyando': '支撑式击弦，手指击弦后停在相邻的弦上',
    'Arrastre': '快速滑弦技巧，从低音向高音滑动',
    'Barré': '横按，用食指同时按压多根弦',
    'Battente': '用手掌击打琴面制造打击乐效果',
    'Campanella': '钟声效果，使用不同把位的空弦和按弦产生重叠音效',
    'Ceja': '横按记号，标记需要横按的把位',
    'Cross-string': '跨弦技巧，在不同弦上演奏旋律',
    'Demi-barré': '半横按，只按压部分弦',
    'Descending rasgueado': '向下扫弦，从高音弦向低音弦方向',
    'Double-stop': '双音技巧，同时按住两个音',
    'Etude': '练习曲，专门用于提高某项技巧的曲目',
    'Fan rasgueado': '扇形扫弦，依次使用多个手指扫弦',
    'Fingerpicking': '指弹技巧，使用手指而不是拨片演奏',
    'Golpe': '击打琴面或琴弦制造打击乐效果',
    'Hammer-on': '锤弦，在已经发声的弦上用力按压产生新音',
    'Harmonics': '泛音技巧，在特定位置轻触琴弦产生泛音',
    'Hinge-barré': '铰链式横按，使用食指第一关节横按',
    'Inverted mordent': '倒波音，主音-上方邻音-主音的快速演奏',
    'Ligado': '连音技巧，包括锤弦和勾弦',
    'Mordent': '波音，主音-下方邻音-主音的快速演奏',
    'Natural harmonics': '自然泛音，在琴弦特定分数点处产生的泛音',
    'Ornament': '装饰音，用于装饰主要旋律的附加音符',
    'Picado': '单音技巧，使用i、m、a指头演奏单个音符',
    'Ponticello': '靠近琴桥处演奏，产生明亮尖锐的音色',
    'Position': '把位，左手在指板上的位置',
    'Pull-off': '勾弦，通过向下勾起手指产生新音',
    'Rasgueado': '扫弦技巧，连续使用多个手指快速扫弦',
    'Slide': '滑弦，从一个音滑向另一个音',
    'Slur': '连音，两个或多个音符连续演奏不间断',
    'Snap pizzicato': '巴托克拨弦，用力拨弦使其撞击指板',
    'Sul ponticello': '靠近琴桥演奏，产生明亮的金属音色',
    'Sul tasto': '靠近指板演奏，产生柔和的音色',
    'Tapping': '双手敲击指板产生音符',
    'Technique': '演奏技巧，包括各种手指动作和发声方法',
    'Tirando': '空弦式击弦，手指击弦后不停在相邻的弦上',
    'Tremolo': '颤音技巧，快速重复演奏同一个音',
    'Trill': '震音，两个相邻音符的快速交替',
    'Vibrato': '(vib.)揉弦，通过左手手指的快速摇动改变音高',
    'vib.': '(Vibtato) 揉弦，通过左手手指的快速摇动改变音高',
    'Artificial harmonics': '人工泛音，通过特殊技巧产生的泛音',
    'Bass string': '低音弦，吉他的第4、5、6弦',
    'Bridge saddle': '琴桥上的骨条，支撑琴弦的部件',
    'Classical position': '古典吉他演奏姿势，使用脚凳抬高左腿',
    'Damping': '制音，使用手掌或手指停止琴弦振动',
    'Extended technique': '扩展技巧，非传统的演奏方法',
    'Fret marker': '品位标记，指板上的位置标记',
    'Guitar support': '吉他支撑架，替代传统脚凳的现代设备',
    'Half-barré': '半横按，只按压部分弦的横按技巧',
    'Index finger': '食指，右手演奏中用i表示',
    'Jump position': '跳把位，快速改变左手位置',
    'Key position': '把位，左手在指板上的位置标记',
    'Left hand position': '左手位置，指左手在指板上的放置位置',
    'Middle finger': '中指，右手演奏中用m表示',
    'Nail shape': '指甲形状，古典吉他演奏者的指甲修剪方式',
    'Open string': '空弦，不按压时的琴弦音',
    'Palm mute': '手掌制音，用手掌轻触琴弦',
    'Quick position': '快速把位转换技巧',
    'Ring finger': '无名指，右手演奏中用a表示',
    'String crossing': '跨弦技巧，在不同弦间移动',
    'Thumb position': '拇指位置，右手拇指的放置位置',
    'Upper position': '高把位，在指板较高位置的演奏',
    'Warm tone': '温暖音色，靠近指板处演奏的音色特征',
    'Xylophone effect': '木琴效果，特殊的演奏技巧模仿木琴音色',
    'Yield point': '让音点，装饰音的结束点',
    'Zero fret': '零品，某些吉他在琴枕位置的金属品',
    'Aguado position': '阿瓜多演奏姿势，一种传统的古典吉他演奏姿势',
    'Barré chord': '横按和弦，使用横按技巧按压的和弦',
    'Capo position': '变调夹位置，变调夹放置的位置',
    'Dolce tone': '甜美音色，一种柔和优美的音色效果',
    'Ergonomic position': '人体工学演奏姿势，现代改良的演奏姿势',
    'Finger independence': '手指独立性，各手指独立运动的能力',
    'Hand angle': '手部角度，左右手相对于琴弦的角度',
    'Intimate tone': '私密音色，极其柔和的演奏音色',
    'Joint flexibility': '关节灵活性，手指关节的活动能力',
    'Knuckle position': '指关节位置，手指关节的放置位置',
    'Lateral movement': '横向移动，左手在指板上的横向移动',
    'Melodic line': '旋律线条，主要旋律的进行方式',
    'Nail angle': '指甲角度，击弦时指甲与弦的角度',
    'Octave harmonic': '八度泛音，在八度位置产生的泛音',
    'Parallel movement': '平行移动，和弦的平行移动技巧',
    'Quick release': '快速放松，击弦后的快速放松动作',
    'Relaxed position': '放松姿势，保持身体放松的演奏姿势',
    'String height': '弦高，琴弦距离指板的高度',
    'Thumb stroke': '拇指击弦，使用拇指演奏的技巧',
    'Upper neighbor': '上邻音，装饰音中高于主音的音',
    'Vertical movement': '垂直移动，手指的上下运动',
    'Wrist position': '手腕位置，右手手腕的放置位置',
    'Alternating bass': '交替低音，在伴奏中交替使用不同的低音',
    'Block chord': '块状和弦，同时按下所有和弦音',
    'Chord melody': '和弦旋律，将旋律和和弦结合的演奏方式',
    'Diagonal movement': '斜向移动，手指在指板上的斜向移动',
    'Expression mark': '表情记号，乐谱中的表现力指示',
    'Finger pattern': '指法模式，特定乐段的固定指法',
    'Grace note': '装饰音，快速演奏的装饰性音符',
    'Hand position': '手位，左右手的基本放置位置',
    'Inner voice': '内声部，多声部音乐中的中间声部',
    'Key change': '转调，音乐中的调式变化',
    'Lower neighbor': '下邻音，装饰音中低于主音的音',
    'Melodic minor': '旋律小调，上行和下行使用不同音阶',
    'Note duration': '音符时值，音符持续的时间长度',
    'Outer voice': '外声部，多声部音乐中的最高或最低声部',
    'Passing tone': '经过音，连接两个主要音符的音',
    'Quarter tone': '四分之一音，比半音还要小的音程',
    'Rest position': '休止位置，演奏间歇时手的放置位置',
    'Tension release': '张弛关系，音乐中的紧张与放松',
    'Unison note': '同音，相同音高的两个音',
    'Voice balance': '声部平衡，多声部间的音量平衡',
    'Walking bass': '行走低音，循序渐进的低音进行',
    'Altered chord': '变化和弦，包含变化音的和弦',
    'Broken chord': '分解和弦，将和弦音依次演奏',
    'Chromatic run': '半音进行，连续的半音音阶片段',
    'Double stop': '双音，同时演奏两个音的技巧',
    'Echo effect': '回声效果，模仿回声的演奏效果',
    'Guide tone': '引导音，和声进行中的关键音',
    'Harmonic minor': '和声小调，小调音阶的一种变体',
    'Implied harmony': '隐含和声，单音旋律暗示的和声',
    'Jazz chord': '爵士和弦，爵士音乐中常用的和弦',
    'Key signature': '调号，乐谱开始处的调式标记',
    'Leading tone': '导音，音阶中的第七音',
    'Modal mixture': '调式混合，大小调色彩的交替使用',
    'Neighbor tone': '邻音，装饰主音的上下相邻音',
    'Ostinato bass': '固定低音，重复的低音模式',
    'Parallel fifth': '平行五度，声部进行中的平行五度关系',
    'Quartal harmony': '四度和声，以四度叠置构成的和声',
    'Relative minor': '关系小调，与大调相关联的小调',
    'Secondary dominant': '副属和弦，非主调的属和弦',
    'Tertian harmony': '三度和声，以三度叠置构成的和声',
    'Unison passage': '齐奏段落，多声部同音进行的段落',
    'Voice crossing': '声部交叉，不同声部音高的交叉关系',
    'Whole tone': '全音，两个相邻全音阶音之间的音程',
    'Added tone': '附加音，和弦中添加的非和弦音',
    'Bridge passage': '过渡段，连接两个主要段落的部分',
    'Cadential': '终止式的，与乐句结束相关的',
    'Diatonic scale': '自然音阶，不含变化音的音阶',
    'Enharmonic note': '异名同音，写法不同但音高相同的音',
    'Final cadence': '最终终止，乐曲结束处的终止式',
    'Ground bass': '固定低音，不断重复的低音音型',
    'Harmonic rhythm': '和声节奏，和声变化的规律',
    'Interval study': '音程练习，针对特定音程的练习',
    'Just intonation': '纯律，基于自然泛音列的调律法',
    'Key center': '调中心，音乐的调性中心',
    'Linear motion': '线性进行，声部的水平移动',
    'Metric accent': '节拍重音，基于节奏的重音',
    'Non-chord tone': '非和弦音，不属于和弦的音',
    'Oblique motion': '斜行，一个声部保持不动而另一个声部移动',
    'Phrase mark': '乐句记号，标示乐句的记号',
    'Quality change': '音质变化，和弦或音程性质的改变',
    'Rhythmic motive': '节奏动机，重复出现的节奏型',
    'Scale degree': '音阶级数，音阶中音的位置序号',
    'Tonal center': '调性中心，音乐的主要调性依归',
    'Unstable tone': '不稳定音，倾向于解决到稳定音的音',
    'Voice leading': '声部进行，多声部音乐中各声部的移动方式',
    'Whole step': '全音，相当于两个半音的音程距离',
    'Altered scale': '变化音阶，包含多个变化音的音阶',
    'Borrowed chord': '借用和弦，从其他调式借用的和弦',
    'Chord symbol': '和弦记号，表示和弦的符号',
    'Dominant prep': '属和弦准备，为属和弦做准备的和弦',
    'Embellishment': '装饰，对基本音符的装饰',
    'Figured bass': '数字低音，巴洛克时期的和声记号',
    'Guide finger': '引导指，换把位时的参考手指',
    'Harmonic series': '泛音列，自然泛音的序列',
    'Inner melody': '内部旋律，和声中的中间声部旋律',
    'Jazz pattern': '爵士句型，典型的爵士乐句模式',
    'Key relation': '调式关系，不同调式间的关系',
    'Lydian mode': '利底亚调式，教会调式之一',
    'Modal chord': '调式和弦，基于特定调式的和弦',
    'Neapolitan': '那不勒斯和弦，小调式中的特殊和弦',
    'Octave study': '八度练习，针对八度音程的练习',
    'Parallel motion': '平行进行，声部同向平行移动',
    'Quintal harmony': '五度和声，以五度叠置构成的和声',
    'Root position': '原位，和弦的基本位置',
    'Scale pattern': '音阶模式，特定的音阶指法模式',
    'Tension chord': '紧张和弦，具有不稳定性的和弦',
    'Upper structure': '上部结构，和弦的上部音组合',
    'Voice exchange': '声部交换，声部之间的位置互换',
    'Whole tone scale': '全音音阶，由全音构成的音阶',
    'Augmented sixth': '增六和弦，包含增六度的特殊和弦',
    'Borrowed mode': '借用调式，从其他调式借用的音阶',
    'Chord voicing': '和弦排列，和弦音的具体排列方式',
    'Diminished scale': '减音阶，由半音和全音交替构成的音阶',
    'Enharmonic chord': '异名同音和弦，写法不同但音高相同的和弦',
    'False relation': '假关系，不同声部间的不协和关系',
    'Guide tone line': '引导音线，和声进行中的关键音进行',
    'Harmonic analysis': '和声分析，分析音乐的和声结构',
    'Inner voice leading': '内声部进行，中间声部的移动方式',
    'Jazz voicing': '爵士和弦排列，爵士风格的和弦排列',
    'Key modulation': '转调，从一个调式转到另一个调式',
    'Linear harmony': '线性和声，基于声部进行的和声',
    'Modal interchange': '调式交替，不同调式的交替使用',
    'Natural minor': '自然小调，小调的基本形式',
    'Octave displacement': '八度移位，将音符移动八度',
    'Parallel harmony': '平行和声，和声的平行移动',
    'Quartal voicing': '四度和声排列，以四度叠置的和声排列',
    'Root movement': '根音进行，和弦根音的移动方式',
    'Scale harmonization': '音阶和声化，为音阶配置和声',
    'Upper neighbor tone': '上邻音，高于主音的装饰音',
    'Voice separation': '声部分离，保持声部间的独立性',
    'Whole step motion': '全音进行，以全音距离移动的进行方式',
    'Accelerado': '渐快',
    'ad libitum': '速度任意',
    'Aentoq': '缓',
    'Affrettando': '再快一些',
    'Allargando': '逐渐变得宽广并渐强（通常用在曲尾）',
    'Allegro Assai': '很快的快板',
    'Allegro Moderato': '中庸的快板',
    'Allegro vivace': '活泼的快板',
    'Andamtte': '行板',
    'Andantino': '小行板；比Andanto稍快；较快的行板',
    'Dcppio movimento': '加快一倍',
    'Larghetto': '小广板；比Largo稍快；较快的小广板',
    'Moderatamente': '中等的；中庸的',
    'Moderato': '中板；适中；节制的',
    'Piu': '更；更多的',
    'Piu allegro': '更多的加快突快',
    'Piu lento': '更慢的',
    'Precipitano': '突然加快匆忙的急促的',
    'Presser': '匆忙；"赶"',
    'Prestissimo': '狂板；最快；极急速的临时转换速度',
    'Ritardato': '放慢了的',
    'Stringendo': '加紧加快',
    'Vivacissimo': '最急板；十分活跃地；非常爽快地',
    'Accel': '渐快',
    'Con forza': '有力的',
    'Con tutta forza': '用全部力量，尽可能响亮地',
    'Declamando': '朗诵般的',
    'Decrescendo': '渐弱',
    'Deliberato': '果断的',
    'Dolente': '悲哀地，怨诉地',
    'Elegance': '优雅的，风流潇洒的',
    'Elegiaco': '哀悼的，挽歌的',
    'Elevato': '崇高的，升华的',
    'Fastoso': '显赫辉煌地，华美地',
    'Fiaccamente': '柔弱的，无力的',
    'Fiero': '骄傲的，激烈的',
    'Flessibile': '柔和而可伸缩的',
    'Fortepiano': '强后突弱',
    'Frescamente': '新鲜地，清新地，年轻地',
    'Fuocoso': '火热的，热烈的',
    'Generoso': '慷慨的，宽宏而高贵的',
    'Gioiante': '快乐的',
    'Giusto': '准确的，适当的',
    'Imitando': '仿拟，模仿',
    'Incalcando': '加急渐快并渐强',
    'Indifferenza': '冷漠',
    'Infantile': '幼稚的，孩子气的',
    'Innig': '内在的，深切的',
    'Innocente': '天真无邪的，坦率无知的，纯朴的',
    'Inquielo': '不安的',
    'Irato': '发怒地',
    'Largamente': '广阔的，浩大地',
    'Leggiere': '轻巧的，轻快的',
    'Luttuoso': '哀痛的',
    'Meno allegro': '速度转慢',
    'Mesto': '忧郁的',
    'Mezzo Forte': '中强',
    'Mezzo Piano': '中弱',
    'Mormorando': '絮絮低语地',
    'Netto': '清爽的，清楚的',
    'Nobile': '高贵的',
    'Pacatamente': '平静地，温和地，安详地',
    'Parlante': '说话似的',
    'Pianoforte': '先弱后强',
    'Piacevole': '愉快的，惬意的，使人悦愉的',
    'Placido': '平静的',
    'Ponderoso': '有力而印象深刻的',
    'Posato': '安祥的，稳重的',
    'Pressante': '紧迫的，催赶的',
    'Riposato': '恬静的',
    'Ritardando': '渐慢',
    'Sciolto': '无拘无束的，流畅的，敏捷的',
    'Sdegnoso': '愤慨的，轻蔑的',
    'Sforzando': '突强',
    'Smania': '狂怒，疯狂',
    'Smorfioso': '做作的，买弄的',
    'Smorzando': '渐弱并渐慢、逐渐消失',
    'Soave': '柔和的，甘美的',
    'Solennemente': '庄严而隆重地',
    'Sonoro': '响亮的',
    'Sotto voce': '轻声的，弱声的',
    'Spirito': '精神饱满的，热情的，有兴致的，鼓舞的',
    'Strappando': '用粗暴的力量来发音',
    'Teneramente': '温柔地，柔情地',
    'Timoroso': '胆怯的，恐惧的，畏惧的',
    'Trionfante': '凯旋的',
    'Tumultuoso': '嘈杂的，喧闹的',
    'Veloce': '敏捷的',
    'Vezzoso': '优美的，可爱的',
    'Violentemente': '狂暴地，猛烈地',
    'Vivente': '活泼的，有生气的',
    'Vivido': '活跃的，栩栩如生的',
    'Zeffiroso': '轻盈柔和的，象微风般的',
    'Accento': '加强地，突强，特重',
    'Forzato': '加强地，突强，特重',
    'Rinforzando': '加强地，突强，特重',
    'Bitonalità': '双调性',
    'Barre': '横按，横压',
    'Capotasto': '变调夹',
    'Harmonic': '泛音',
    'Natural harmonic': '自然泛音',
    'Artificial harmonic': '人工泛音',
    'Pizzicato': '拨奏，闷音',
    'Bend': '推弦',
    'Release': '放弦',
    'Pre-bend': '预推弦',
    'Unison bend': '同音推弦',
    'Pinch harmonic': '人工泛音（挤压式）',
    'Sweep picking': '扫拨',
    'Economy picking': '经济拨片法',
    'Alternate picking': '交替拨片法',
    'String skipping': '跳弦',
    'Hybrid picking': '混合拨奏法',
    'Travis picking': '特拉维斯指法',
    'Artificial harmonic slide': '人工泛音滑音',
    'Legato slide': '连奏滑音',
    'Shift slide': '换把滑音',
    'Ghost note': '装饰音，幽灵音',

    # 巴洛克时期
    'Allemande': '德国舞曲（巴洛克组曲中的第一乐章）',
    'Aria da capo': '带反复的咏叹调',
    'Bourree': '布雷舞曲（法国快速舞曲）',
    'Cantus firmus': '定旋律（固定音调）',
    'Chaconne': '恰空舞曲（庄严的三拍子）',
    'Concerto grosso': '大协奏曲',
    'Courante': '库朗特舞曲（法国快速舞曲）',
    'Gavotte': '加沃特舞曲（法国舞曲）',
    'Gigue': '吉格舞曲（快速的复拍子舞曲）',
    'Menuet': '小步舞曲',
    'Passacaglia': '帕萨卡利亚（庄严的变奏曲）',
    'Pavane': '孔雀舞曲（庄重的舞曲）',
    'Ricercare': '里切卡雷（复调音乐）',
    'Sarabande': '萨拉班德舞曲（庄严的舞曲）',
    'Toccata': '托卡塔（炫技性乐曲）',

    # 古典主义时期
    'Cadenza': '华彩段',
    'Divertimento': '嬉游曲',
    'Eingang': '引入句（德语）',
    'Exposition': '呈示部',
    'Galant': '优雅的风格',
    'Hauptsatz': '主题（德语）',
    'Mannheimer Schule': '曼海姆乐派',
    'Rondo': '回旋曲',
    'Seitensatz': '副主题（德语）',
    'Serenata': '小夜曲',
    'Sinfonia': '交响曲',
    'Sonatina': '小奏鸣曲',
    'Sturm und Drang': '狂飙运动（德语）',

    # 浪漫主义时期
    'Albumblatt': '相册页（德语）',
    'Ballade': '叙事曲',
    'Berceuse': '摇篮曲（法语）',
    'Capriccio': '随想曲',
    'Charakterstück': '性格小品（德语）',
    'Consolation': '安慰曲（法语）',
    'Fantasie': '幻想曲（德语）',
    'Impromptu': '即兴曲（法语）',
    'Innigkeit': '内在的，深情的（德语）',
    'Intermezzo': '间奏曲',
    'Leidenschaftlich': '热情地（德语）',
    'Lied ohne Worte': '无词歌（德语）',
    'Märchen': '童话（德语）',
    'Moment musical': '音乐瞬间（法语）',
    'Nachtstück': '夜曲（德语）',
    'Nocturne': '夜曲（法语）',
    'Novellette': '小说曲',
    'Rhapsodie': '狂想曲',
    'Romanze': '浪漫曲（德语）',
    'Schwungvoll': '充满激情地（德语）',
    'Sehnsucht': '渴望（德语）',
    'Träumerei': '梦幻曲（德语）',
    'Waldszenen': '森林景象（德语）',
    'Zeitmaß': '速度（德语）',

    # 意大利语专业术语
    'A capriccio': '随意地',
    'A piacere': '随心所欲地',
    'Abbandono': '放任的',
    'Acciaccatura': '短倚音',
    'Affannato': '焦虑的',
    'Agilità': '灵活的',
    'Con abbandono': '放纵地',
    'Con alcuna licenza': '带有一些自由',
    'Con amore': '充满爱意地',
    'Con bravura': '技巧性地',
    'Con calore': '热情地',
    'Con delicatezza': '细腻地',
    'Con dolcezza': '甜美地',
    'Con duolo': '悲伤地',
    'Con eleganza': '优雅地',
    'Con espressione': '富有表情地',
    'Con fierezza': '自豪地',
    'Con fuoco': '火热地',

    # 法语专业术语
    'À deux mains': '双手的',
    'À plein son': '全音的',
    'Avec âme': '有灵魂地',
    'Avec chaleur': '热情地',
    'Avec douleur': '悲痛地',
    'Avec éclat': '辉煌地',
    'Avec élan': '热情奔放地',
    'Avec émotion': '激动地',
    'Avec grâce': '优美地',
    'Avec largeur': '宽广地',
    'Avec passion': '热情地',
    'Brillamment': '辉煌地',
    'Chantant': '如歌的',
    'Délicatement': '精致地',
    'Doucement': '温柔地',
    'En dehors': '突出地',
    'Gracieusement': '优雅地',
    'Légèrement': '轻盈地',
    'Passionnément': '热情地',
    'Sans rigueur': '自由地',

    # 德语专业术语
    'Ausdruck': '表情',
    'Ausdrucksvoll': '富有表情地',
    'Bewegt': '激动的',
    'Dämpfer': '弱音器',
    'Einfach': '简单地',
    'Empfindung': '感觉',
    'Entfernt': '远离的',
    'Entschieden': '坚决地',
    'Erhaben': '崇高的',
    'Feurig': '火热地',
    'Fließend': '流畅地',
    'Gebunden': '连奏的',
    'Gefühlvoll': '感情丰富地',
    'Gehalten': '持续的',
    'Gemächlich': '从容地',
    'Gesangvoll': '如歌的',
    'Getragen': '庄重地',
    'Gewichtig': '重要地',
    'Heftig': '激烈地',
}


# 构建中文到术语的反向映射
chinese_to_english = {value: key for key, value in music_terms.items()}

# 近义词映射
synonyms = {
    # 恢复原速相关
    '恢复原速': ['回到原速', '原速', '还原速度'],

    # 加速相关
    '加速': ['渐快', '更快', '迅速'],
    '渐快': ['加速', '更快的', '逐渐快'],

    # 缓慢相关
    '缓慢': ['慢', '柔缓', '优雅'],

    # 深情相关
    '深情': ['柔情', '感人', '深刻'],

    # 优雅相关
    '优雅': ['柔美', '高雅', '典雅'],

    # 快速相关
    '快速': ['迅速', '活泼', '轻快'],
    '非常快速': ['极快', '迅捷', '快速的'],

    # 生动相关
    '生动': ['活跃', '有活力', '充满生命力'],
    '充满激情': ['激情四溢', '热情洋溢', '热烈'],

    # 歌唱相关
    '歌唱': ['歌颂', '歌声', '旋律优美'],

    # 清晰相关
    '清晰': ['明晰', '清楚', '明确'],

    # 渐强相关
    '渐强': ['加强', '增强', '逐渐响亮'],

    # 渐弱相关
    '渐弱': ['逐渐变弱', '弱化', '声音逐渐消失'],

    # 动感相关
    '动感': ['有节奏感', '活泼', '更有力度'],

    # 停顿相关
    '停顿': ['暂停', '停止', '中断'],

    # 强相关
    '强': ['有力', '响亮', '力度强'],

    # 庄严相关
    '庄严': ['威严', '隆重', '宏伟'],

    # 神秘相关
    '神秘': ['隐秘', '不可思议', '奇妙'],

    # 平静相关
    '平静': ['安宁', '宁静', '和缓'],

    # 愤怒相关
    '愤怒': ['狂暴', '激烈', '愤慨'],

    # 断奏相关
    '断奏': ['短促', '清晰的音符', '跳跃'],

    # 柔和相关
    '柔和': ['优美', '细腻', '和谐'],

    # 简单相关
    '简单': ['易懂', '简洁', '朴素'],

    # 自由相关
    '自由': ['随意', '不拘束', '自由变化'],
    
    # 忽然相关
    '突然': ['突兀', '忽然', '出其不意'],

    # 飞快相关
    '飞快': ['迅速', '快速移动', '急速'],

    # 感伤相关
    '感伤': ['悲怆', '忧伤', '深刻的情感'],

    
    '甜美的，柔和的': ['甜','甜美','甜美的'],


}

# 去除助词
def remove_particles(text):
    return text.replace('的', '').replace('地', '').replace('得', '')

# 查询音乐术语
def query_term(term):
    # 替换中文全角句号为英文句号
    term = term.replace('。', '.')
    
    # 转换为小写，进行不区分大小写的匹配
    term_lower = term.lower()
    
    # 构建大小写无关的词典映射
    lower_to_original = {key.lower(): key for key in music_terms.keys()}
    
    # 精确匹配：不区分大小写
    if term_lower in lower_to_original:
        original_key = lower_to_original[term_lower]
        return f"匹配到精确术语：{original_key}，解释为：{music_terms[original_key]}"
    
    # 中文精确匹配
    if term in chinese_to_english:
        return f"匹配到精确中文：{term}，对应术语是：{chinese_to_english[term]}"
    
    # 去除助词后进行中文模糊匹配
    term_no_particles = remove_particles(term)
    processed_terms = {remove_particles(k): k for k in chinese_to_english.keys()}
    if term_no_particles in processed_terms:
        original_key = processed_terms[term_no_particles]
        return f"匹配到模糊中文：{original_key}，对应术语是：{chinese_to_english[original_key]}"
    
    # 近义词匹配
    for key, syn_list in synonyms.items():
        if term in syn_list:
            if key in chinese_to_english:
                return f"匹配到近义词：{term}（近义词为：{key}），对应术语是：{chinese_to_english[key]}"
    
    # 拼音模糊匹配
    term_pinyin = ''.join(pypinyin.lazy_pinyin(term))
    chinese_pinyin_map = {''.join(pypinyin.lazy_pinyin(k)): k for k in chinese_to_english.keys()}
    close_pinyin_matches = difflib.get_close_matches(term_pinyin, chinese_pinyin_map.keys(), n=5, cutoff=0.6)
    if close_pinyin_matches:
        return "没有找到精确匹配的中文解释，但根据拼音匹配以下结果：\n" + \
               "\n".join([f"{chinese_pinyin_map[match]}: {chinese_to_english[chinese_pinyin_map[match]]}" for match in close_pinyin_matches])
    
    return "没有找到与该术语相关的任何内容。"

    # 模糊匹配：大小写无关
    close_matches = difflib.get_close_matches(term_lower, lower_to_original.keys(), n=5, cutoff=0.6)
    if close_matches:
        return "没有找到精确匹配的术语。以下是最接近的5个术语：\n" + \
               "\n".join([f"{lower_to_original[match]}: {music_terms[lower_to_original[match]]}" for match in close_matches])
    else:
        return "没有找到与该术语相关的任何内容。"


# 主程序
def main():
    print("欢迎使用音乐术语词典！由yuze研发，完全开源。")
    while True:
        term = input("请输入音乐术语或中文解释（或输入'dc1'退出）：")
        if term.lower() == 'dc1':
            print("谢谢使用，尊敬的音乐家，愿您在音乐的道路上继续前行。再见！")
            break
        translation = query_term(term)
        print(f"{term} 的查询结果是：\n{translation}\n")

if __name__ == "__main__":
    main()
